apiVersion: apps/v1
kind: Deployment
metadata:
  name: elemental-operator
spec:
  selector:
    matchLabels:
      app: elemental-operator
  template:
    metadata:
      labels:
        app: elemental-operator
    spec:
      containers:
      - env:
        - name: NO_PROXY
          value: {{ .Values.noProxy }}
        {{- if .Values.proxy }}
        - name: HTTP_PROXY
          value: {{ .Values.proxy }}
        - name: HTTPS_PROXY
          value: {{ .Values.proxy }}
        {{- end }}
        name: elemental-operator
        imagePullPolicy: "{{ .Values.image.imagePullPolicy }}"
        image: {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        args:
        - operator
        {{- if .Values.debug }}
        - --debug
        {{- end }}
        - --namespace
        - {{ .Release.Namespace }}
        {{- if .Values.sync_namespaces}}
        - --sync-namespaces
        - {{ .Values.sync_namespaces }}
        {{- end }}
        - --sync-interval
        - {{.Values.sync_interval }}
        - --operator-image
        - {{ template "system_default_registry" . }}{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}
        - --default-registry
        - {{ .Values.global.cattle.systemDefaultRegistry | quote }}
        - --rancher-server-url
        - {{ .Values.global.cattle.url | quote }}
        - --ca-cert
        - {{ .Values.global.cattle.ca_cert | quote }}
      serviceAccountName: elemental-operator
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
